apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        resources:
          limits: 
            memory: 2048Mi
        ports:
        - containerPort: 9200
        env:
        - name: "discovery.type"
          value: "single-node"
        - name: "node.roles"
          value: "[ master, data ]"
        - name: "xpack.security.enabled"
          value: "false"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1024m -Xmx1024m"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
      volumes:
      - name: es-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - protocol: "TCP"
    port: 9200
    targetPort: 9200
    nodePort: 30800


